### ISSUE TITLE
Feature: make “Parse To Type” public

### ISSUE THREAD

**Issue by drjdpowell** [JKISoftware/JKI-JSON-Serialization#10]
JKSH on LAVA [suggested a use case](https://lavag.org/topic/16217-cr-json-labview/?do=findComment&comment=119583) where he wants to convert JSON into a Variant form of strings/numbers/booleans, and then pass that across a code boundary to some other component that actually knows the true type to use.   This is how your library actually works under the public API, and it has a private “Parse to Type” function.  So you could easily support this use case if you made that method publicly accessible.

**Comment by tmaila** [comment]
Implemented in build 1.0.4.21. Still missing documentation.
