### ISSUE TITLE
Reading raw JSON string into LabVIEW string

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-JSON-Serialization#11]
Similar to this EasyXML feature: [Reading Raw XML into strings using the "#xml" suffix in string label/name](https://github.com/JKISoftware/JKI-EasyXML#reading-raw-xml-into-strings-using-the-xml-suffix-in-string-labelname)

It would be useful to have the ability to read an entire raw JSON element into a string data type in LabVIEW, which can then be separately parsed (e.g. this would be helpful for [multi-dimensional JSON arrays](https://github.com/JKISoftware/JKI-JSON-Serialization/issues/5) that have differing row/column lengths).

To do this, we could name (label) the string with an " #raw" or "#JSON" suffix. The result would be that the raw JSON data will be read into/from the string and then can be processed in a separate step. This is especially helpful if elements (having the same name) come in a few different flavors (sub-element types and structure). See the EasyXML examples, below:

![EasyXML example](https://cloud.githubusercontent.com/assets/381432/17980227/0f67281a-6ab3-11e6-80ca-78b06b9cdaed.png)

**Comment by tmaila** [comment]
The same problem this proposal would solve can already be solved with JKI JSON as the deserialization is a two step process. An element can be deserialized into a variant that can hold a full hierarchy of objects. That variant can then be adapted to specific type using Adapt to Type method. This allows traversing the parse tree element by element and choosing at runtime to what type to deserialize that element based on for example other items that have already been deserialized. Further multidimensional LabVIEW arrays are supported in release 1.0.7.
