### ISSUE TITLE
value of "empty object" not supported

### ISSUE THREAD

**Issue by rockethacker** [JKISoftware/JKI-JSON-Serialization#12]
@tmaila the solution implemented in #7 does not work for all cases.

In this case, it still throws an error.
![labview_2016-08-25_15-20-27](https://cloud.githubusercontent.com/assets/6414570/17985602/2a759866-6adc-11e6-96d4-fcc9e6b28a7e.png)

The root cause of this issue is due to the fact that LabVIEW cannot represent a data type of "empty cluster". #7 didn't fix the issue because it ended up changing the data type of the parsed "empty cluster" as "empty variant" which causes the downstream functions view this as a datatype mismatch. i believe that the correct solution to this problem is to ignore any "empty cluster" items since they can't be represented by a variant.

I recommend that the change in #7 be reverted and the fix be implemented as follows:
![labview_2016-08-25_15-36-51](https://cloud.githubusercontent.com/assets/6414570/17985617/383b6e76-6adc-11e6-8e43-17b99d3f1c59.png)

i think that the above fix will also resolve #9

**Comment by tmaila** [comment]
@rockethacker in JSON null and {} and synonyms. The JSON parsing using JKI JSON is a two step process. In the first step the JSON is parsed into a representative LabVIEW data type. There {} and null must be parsed into the same data type, which has to be empty variant, the only "null" type in LabVIEW. The second question is how to parse this into a specific type when cluster is passed as the type hint. I think we should add a null value to be deserializable to a cluster and that would just return the default value you have passed as the argument.

**Comment by jimkring** [comment]
I like having an option for null JSON to deserialize to the default LabVIEW
value wired in.

Also, in some cases where different JSON types might appear, it would be
nice to be able to extract the raw JSON string (Reading raw JSON string
into LabVIEW string #11)

**Comment by rockethacker** [comment]
@tmaila i'm on the same page now. agreed that null needs to be supported also.

so we should disregard by suggested change above and instead fix by modifying the "variant to variant mapping" algorithm.

the change i made above does not address this case (i think i may have hit all of the corner cases now)
![labview_2016-08-26_17-49-32](https://cloud.githubusercontent.com/assets/6414570/18022804/9c32ec52-6bb7-11e6-8d23-d4d0de4df1ba.png)

i think this is the change that needs to be made. it has proven to fix the issue on my side.
![labview_2016-08-26_17-24-13](https://cloud.githubusercontent.com/assets/6414570/18022813/ab0e4e74-6bb7-11e6-8159-e3c527f3c14f.png)

note that all cases i've reported in this ticket I have been observed in the real world while writing a jira api LabVIEW wrapper. i have made local modifications to get me through these bugs, but we'll need a published fix pretty soon. thanks for the support!

**Comment by tmaila** [comment]
Same as #17.
