### ISSUE TITLE
Icon for "Null Value.vi" should be "null" not "{}"

### ISSUE THREAD

**Issue by robertbcalhoun** [JKISoftware/JKI-JSON-Serialization#19]
JSON nulls and JSON empty ~~string~~ object are not the same thing. Icon should use the word "null", not "{}", to describe a null. (Content is correct, it's just the icon that is confusing.) 

![null values](https://cloud.githubusercontent.com/assets/5921027/18179735/b352c314-7038-11e6-8407-7285d7433289.png)

See similar files in https://github.com/robertbcalhoun/JKI-JSON-Serialization/tree/feature/variant-attributes-1.1.2

**Comment by tmaila** [comment]
How would you represent empty clusters in LabVIEW?

**Comment by tmaila** [comment]
Fixed in build 1.1.3 that adds support for empty objects and separates them for null objects.

**Comment by robertbcalhoun** [comment]
You are a bugfixing monster!

I represent empty objects / empty clusters using a void variant, see my fork. It's a very natural use, in that a void variant with no attributes maps to {}, a void variant with one attribute to {"key":"value"} etc. 

There is one issue, which is that void variants can't have names associated with them. That doesn't matter in my variant attribute code, because the top-level JSON object doesn't have a name and below I use attribute names to hold the name rather than a LabView datatype name. But when trying to convert void variants back to strongly-typed LabView data, I ran into an issue because the OpenG "name variant" feature throws an error if passed a void variant. Fixable, but it required changing more core code than I wanted to change given the challenges of merging LabView code.

I'll take a look at your code and see how you addressed this.

**Comment by tmaila** [comment]
I had some unusual downtime so I tried to fix as many bugs as I could before it gets busy again.
