### ISSUE TITLE
Always use decimal point for floating points (ignore local setting)

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-JSON-Serialization#21]
For LabVIEW users using a comma as the decimal point, the JSON Serializer float number is converted to "3,123". In an array this would look like this: "1,111, 2,22, 3,33". This leads to incorrect read-back in of the data.

The following minor change would set this right: 
=> In VI "JKI JSON Serialization.lvlib:JSON Serializer.lvclass:Flatten To String.vi 
=> In cases "Single Float", "Double Float" and "Extended Float, Fixed Point" 
=> change format specifier from "%_6f" to "%.;%0.6f" (this will ensure a point as decimal point in the string.

**Comment by tmaila** [comment]
Fixed in build 1.1.6 where both floating point and timestamp formats were modified to work appropriately on systems that use localized floating point formats.
