### ISSUE TITLE
String data with value containing nested quotes failed to parse

### ISSUE THREAD

**Issue by ghost** [JKISoftware/JKI-JSON-Serialization#23]
For instance, the following json string would fail to parse.
`{"today quote":"John said "Hello world" to JKI","published":true}`

It seemed the library tried to parse character by character and emitted too soon the result. Ideally, whenever a value is enclosed in quote it should enclose whatever value in it, up to the full length of value data.

**Comment by JKSH** [comment]
> `{"today quote":"John said "Hello world" to JKI","published":true}`

The JSON specification requires embedded quotation marks to be escaped. The correct way to encode your object is `{"today quote":"John said \"Hello world\" to JKI","published":true}`

You can check the validity of a JSON string at https://jsonlint.com

**Comment by ghost** [comment]
Thank you for the explanation. I understood that proper json string must be provided.
