### ISSUE TITLE
Deserialising JSON with variable property names

### ISSUE THREAD

**Issue by TAGC** [JKISoftware/JKI-JSON-Serialization#26]
I'm trying to deserialise a JSON document containing variable field names, and I'm unsure how to do this using JKI JSON.

For example, consider the following document:

```json
{
    "abs_bar": {
        "messageId": 500,
        "canPort": 1,
        "repeatRate": 50
    },
    "foo": {
        "messageId": 10,
        "canPort": 0,
        "repeatRate": 50
    }
}
```

I don't know the fields of the document in advance - I'd like to deserialise this to a dictionary where the key is the "message definition name" and the value is a "message definition" cluster, and go from there. I've been able to do this pretty easily in Python and C#, but unfortunately LabVIEW is not a very nice language and most things take a lot more effort in it.

LabVIEW does not have the native concept of a "map", so I attempted to deserialise this as an array of clusters, where each cluster contains a string (for the name) and a "message definition" cluster.

![json deserialisation snippet](https://user-images.githubusercontent.com/1588951/29812787-ba516a60-8c9f-11e7-9a27-113d5de81078.png)

I didn't really expect this to work and it doesn't seem to. This is what I see on the front panel after running this:

![image](https://user-images.githubusercontent.com/1588951/29812845-f303e0b8-8c9f-11e7-8956-cc75600b1643.png)

What's the proper way to go about this?

**Comment by JKSH** [comment]
@TAGC Launch the VI Package Manager and install the OpenG toolkit. Pass your unflattened variant into `Get Cluster Element Names.vi` -- this will give you an array of names of your 2 top-level objects: ["abs_bar", "pressure_reading"]. Then, pass the variant and one field name into `Get Cluster Element by Name.vi` to extract your child object.

FYI, a LabVIEW cluster is analogous to a JSON object. In your code, you put a string + cluster inside an array inside a cluster inside a cluster, which conceptually converts to this document:

```
{
	"": {
		"": [
			{
				"": "",
				"txDefinition": {
					"repeatRate": 0,
					"canPort": 0,
					"messageId": 0
				}
			}
		]
	}
}
```

**Comment by TAGC** [comment]
@JKSH Thanks, that's helped me out!

Here's what I've got:

![json deserialisation snippet 2](https://user-images.githubusercontent.com/1588951/29816387-d1a4aa72-8cab-11e7-8fe5-45eae51ea680.png)

And here's the result, working as intended:

![labview_2017-08-29_11-19-20](https://user-images.githubusercontent.com/1588951/29816433-e9da75b8-8cab-11e7-88ad-e310edda1343.png)

**Comment by TAGC** [comment]
Actually, it's not quite there yet. I should be using the JSON deserialisation library again on the second step - otherwise it mixes up the fields.

**Comment by TAGC** [comment]
Got it:

![json deserialisation snippet 3](https://user-images.githubusercontent.com/1588951/29817151-c47a612c-8cae-11e7-9ae7-701ca443d2c0.png)

Just needed to chuck an `Adapt To Type.vi` in the middle.

This properly handles the case where the properties in the JSON document are in mixed-up order (as it should, since JSON object key/value pairs are meant to be treated as unordered).

![labview_2017-08-29_11-41-57](https://user-images.githubusercontent.com/1588951/29817201-14f0e69e-8caf-11e7-8ec9-882f137bb53c.png)

**Comment by francois-normandin** [comment]
This one will work with your initial JSON string.
Note that it uses "Cluster to Array of VData" from the OpenG palette instead, so you don't need to add the definition name in an extra level.

![image](https://user-images.githubusercontent.com/11728548/29818647-a403bcc2-8cbd-11e7-835e-f0ed970d26a7.png)

![image](https://user-images.githubusercontent.com/11728548/29818674-c4fe1cec-8cbd-11e7-8968-764149b91229.png)

**Comment by PrateekGoyal18** [comment]
Hey @TAGC and  @francois-normandin , my json data is something like this 
{
  "Currents" : {
    "I1" : 2.412445,
    "I2" : 2.607605,
    "I3" : 2.655672
  },
  "Date" : "15-11-2019",
  "Frequency" : 49.99259,
  "Power Factors" : {
    "Q1" : 0.997155,
    "Q2" : 1,
    "Q3" : 0.988455
  },
  "Powers" : {
    "KA1" : 466.713,
    "KA2" : 517.551,
    "KA3" : 533.6165,
    "KT1" : 465.3853,
    "KT2" : 517.551,
    "KT3" : 527.4558,
    "KV1" : 35.17823,
    "KV2" : 0,
    "KV3" : 80.85116
  },
  "THDs" : {
    "THDC1" : 64.92453,
    "THDC2" : 59.34635,
    "THDC3" : 54.73608,
    "THDV1" : 1.798943,
    "THDV2" : 2.569078,
    "THDV3" : 1.955434
  },
  "Time" : "10-27-11am",
  "Voltages" : {
    "V1" : 231.1034,
    "V12" : 400.4179,
    "V2" : 231.2728,
    "V23" : 400.3139,
    "V3" : 230.767,
    "V31" : 400.1738
  }
}

And I need to retrieve the value of each individual field like I2, V23 etc and store them in a variable or an array. Can you help me out to do this ?

**Comment by TAGC** [comment]
@PrateekGoyal18 Afraid not sorry, I don't work with LabVIEW anymore.

**Comment by francois-normandin** [comment]
@PrateekGoyal18 
You simply have to build a cluster of the information matching your JSON string.
In this example, I just added Currents>>I1

![image](https://user-images.githubusercontent.com/11728548/68946211-5ca8dc00-0780-11ea-84e4-8d8b93cc8fdb.png)

And then added some "Powers" cluster as well. You can create a typedef that matches your expected JSON string content and retrieve only those you need.

![image](https://user-images.githubusercontent.com/11728548/68946322-b3aeb100-0780-11ea-9327-f26e5e84843d.png)

**Comment by PrateekGoyal18** [comment]
@francois-normandin really thanks for the solution. It worked like a charm and I can't be more thankful to you.
