### ISSUE TITLE
Incorrect indentation when treating cluster as an ordered array

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-JSON-Serialization#31]

**Comment by jimkring** [comment]
Before fix:
![image](https://user-images.githubusercontent.com/381432/30649908-2638fc5e-9de7-11e7-8c31-c78450d4b818.png)

After fix:
![image](https://user-images.githubusercontent.com/381432/30649809-e279f162-9de6-11e7-9254-ec3c50037d0d.png)

**Comment by jimkring** [comment]
Fixed in next release

**Comment by robertbcalhoun** [comment]
Hi Jim,

The test case for issue #31 is missing from branch master, but "Test Github Issues.vi" references it.
