### ISSUE TITLE
Cluster -> Array -> Cluster -> Timestamp deserialization issue

### ISSUE THREAD

**Issue by alexgieg** [JKISoftware/JKI-JSON-Serialization#33]
Trying to deserialize a timestamp within a cluster within an array within a cluster:

![image](https://user-images.githubusercontent.com/1074619/51551028-c1dbbb80-1e54-11e9-8577-25b06475ad99.png)

Results in an empty array of variants:

![image](https://user-images.githubusercontent.com/1074619/51551116-efc10000-1e54-11e9-9048-7c312755e552.png)

**Comment by jimkring** [comment]
Thanks for reporting this @alexgieg. Can you please attache your VI, zipped? That'll be a big help for others who want to reproduce.

**Comment by alexgieg** [comment]
Oops! Sorry. Here it is: [Test Timestamp.zip](https://github.com/JKISoftware/JKI-JSON-Serialization/files/2787135/Test.Timestamp.zip)

**Comment by jimkring** [comment]
This appears to be fixed by one of the other fixes: #28 #29 #30
I'm going to close this, but LMK if it's still an issue after we release v2.0
