### ISSUE TITLE
Empty multidimensional arrays are incorrectly serialized

### ISSUE THREAD

**Issue by andreas-rydefalk** [JKISoftware/JKI-JSON-Serialization#37]
I noticed that empty multidimensional arrays are incorrectly serialized. They are serialized as just one pair of square brackets regardless of the array dimension (tried 2D and 3D). This results in an error when deserializing the JSON string. 
![image](https://user-images.githubusercontent.com/70474199/93388835-fc893780-f873-11ea-941d-a2875da7b41b.png)
I have JKI JSON 1.1.10.37 installed

**Comment by jimkring** [comment]
Fixed in 2.0.1
