### ISSUE TITLE
JSON Deserializer\Adapt To Type.vi doesn’t handle Boolean

### ISSUE THREAD

**Issue by thomasliebenau** [JKISoftware/JKI-JSON-Serialization#38]
While JSON Serializer\Flatten To String.vi converts a boolean into true/false, the handling of boolean types in JSON Deserializer\Adapt To Type.vi is completely missing.

![image](https://user-images.githubusercontent.com/25008402/109833460-9174c700-7c41-11eb-9bcc-f44e79cfb237.png)

**Comment by francois-normandin** [comment]
@thomasliebenau 
Adaptation to type is for adapting similar datatypes such as U32 to U8, which have the same JSON representation.
Boolean has a unique representation that cannot be mistaken for any other type, so no adaptation is required.

**Comment by thomasliebenau** [comment]
sorry, found my issue - a nasty spelling issue in my JSON string
