### ISSUE TITLE
Flattening empty variants (to null) within an array produces excessive indentation in the output string

### ISSUE THREAD

**Issue by JKSH** [JKISoftware/JKI-JSON-Serialization#6]
_(LabVIEW 2013 SP1 + JKI JSON Serialization v1.0.1.18)_

Suppose I provide this JSON string:

```
[
    "Hello",
    42,
    false,
    null,
    {
        "nested?": true
    }
]
```

Unflattening and then re-flattening it (with Multiline==TRUE) produces

```
[
    "Hello",
    42,
    false,
        null,
    {
        "nested?":true
    }
]
```

Notice that the "null" has too much indentation.

**Comment by tmaila** [comment]
Fixed in 1.0.5
